"""empty message

Revision ID: 459442c25602
Revises: ec6f15925e3c
Create Date: 2019-12-08 03:47:40.391927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '459442c25602'
down_revision = 'ec6f15925e3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'admin')
    # ### end Alembic commands ###
