"""empty message

Revision ID: 619958eead50
Revises: ad681034a774
Create Date: 2019-12-22 03:01:03.511406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '619958eead50'
down_revision = 'ad681034a774'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=50), nullable=True),
    sa.Column('complete', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('name', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'name')
    op.drop_table('todo')
    # ### end Alembic commands ###
